language: cpp
dist: trusty
sudo: false


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - valgrind

matrix:
  include:
    - os: linux
      compiler: gcc

script:
  - source .env
  - make third_party
  - make run-test-valgrind
  - make check-style