language: cpp
dist: trusty
sudo: false

before_install:
  - pip install --user cpp-coveralls

addons:
  apt:
    packages:
      - valgrind

matrix:
  include:
    - os: linux
      compiler: gcc

script:
  - source .env
  - make third_party
  - make run-test-valgrind
  - make check-style
  - make examples
  - make solvers

after_success:
  - coveralls --exclude lib --exclude tests --exclude third_party --exclude examples  --gcov-options '\-lp'