language: cpp
dist: trusty
sudo: false

before_install:
  - pip install --user cpp-coveralls

addons:
  apt:
    packages:
    - valgrind

matrix:
  include:
    - os: linux
      compiler: gcc

before_script:
  - if [[ $TRAVIS_BRANCH == 'master' ]]
    then
        wget https://lip6.fr/Hakan.Metin/fully_sym.zip
        unzip fully_sym.zip
    fi

script:
  - source .env
  - make third_party
  - make run-test-valgrind
  - make check-style
  - make examples
  - make solvers
  - if [[ $TRAVIS_BRANCH == 'master' ]] && ./scripts/execute_bench fully_sym 30 ./bin/minisat

after_success:
  - coveralls --exclude lib --exclude tests --exclude third_party --exclude examples  --gcov-options '\-lp'