#!/bin/bash
set -u

function check_exist_or_die {
    [ -e "$1" ] || { echo "file not exist: $1"; exit 1; }
}

if [[ $# -lt 3 ]]
then
    echo "Usage: $0 PROBLEMS_DIR TIMEOUT SOLVER [SOLVER_OPTIONS]" >&2
    exit 1
fi


PROBLEMS_DIR="$1"; shift
TIMEOUT="$1";      shift
SOLVER="$1";       shift
OPTIONS="$@"

PARALLEL_TASK=2

check_exist_or_die "$PROBLEMS_DIR"
check_exist_or_die "$SOLVER"


find "$PROBLEMS_DIR" -iname "*.cnf" -type f -print0 | \
    xargs -0 -L1 -I {} --max-procs=${PARALLEL_TASK} sh -c \
          "./scripts/execute_solver \"$SOLVER\" \"{}\" $TIMEOUT \"$OPTIONS\""
